### ISSUE TITLE
Ощибка с кошельком

### ISSUE THREAD

**Issue by dram1008** [dram1008/i-am-avatar#1]
exception 'Blocktrail\SDK\Connection\Exceptions\MissingEndpoint' with message 'The endpoint you've tried to access does not exist. Check your URL.' in /home/g/galaxysss/galaxysss/vendor/blocktrail/blocktrail-sdk/src/Connection/RestClient.php:274
Stack trace:
#0 /home/g/galaxysss/galaxysss/vendor/blocktrail/blocktrail-sdk/src/Connection/RestClient.php(246): Blocktrail\SDK\Connection\RestClient->responseHandler(Object(GuzzleHttp\Message\Response))
#1 /home/g/galaxysss/galaxysss/vendor/blocktrail/blocktrail-sdk/src/Connection/RestClient.php(127): Blocktrail\SDK\Connection\RestClient->request('GET', 'wallet/', NULL, NULL, 'http-signatures', NULL, NULL)
#2 /home/g/galaxysss/galaxysss/vendor/blocktrail/blocktrail-sdk/src/BlocktrailSDK.php(687): Blocktrail\SDK\Connection\RestClient->get('wallet/', NULL, 'http-signatures')
#3 /home/g/galaxysss/galaxysss/vendor/blocktrail/blocktrail-sdk/src/BlocktrailSDK.php(657): Blocktrail\SDK\BlocktrailSDK->getWallet(NULL)
#4 /home/g/galaxysss/galaxysss/models/User.php(628): Blocktrail\SDK\BlocktrailSDK->initWallet(NULL, NULL)
#5 /home/g/galaxysss/galaxysss/controllers/CabinetWalletBtcController.php(327): app\models\User->getBitCoin()
#6 [internal function]: app\controllers\CabinetWalletBtcController->actionBalanceInternal()
#7 /home/g/galaxysss/galaxysss/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /home/g/galaxysss/galaxysss/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 /home/g/galaxysss/galaxysss/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('balance-interna...', Array)
#10 /home/g/galaxysss/galaxysss/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('cabinet-wallet-...', Array)
#11 /home/g/galaxysss/galaxysss/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#12 /home/g/galaxysss/galaxysss/public_html/index.php(14): yii\base\Application->run()
#13 {main}

**Comment by dram1008** [comment]
\app\controllers\CabinetWalletBtcController::actionBalanceInternal
```
        /** @var \app\models\User $user */
        $user = Yii::$app->user->identity;
        $wallet = $user->getBitCoin();
        list($confirmedBalance, $unconfirmedBalance) = $wallet->getBalance();
        $confirmedBalance1 = ($confirmedBalance + $unconfirmedBalance) / 100000;
```

**Comment by dram1008** [comment]
![2017-03-21_22-54-04](https://cloud.githubusercontent.com/assets/8858319/24167832/5011657c-0e89-11e7-9d22-591a79263d2c.png)
9487

**Comment by dram1008** [comment]
Поправил
и добавил дебаг инфо
gs\\hasBitCoin
